# Header
menu:
  Home: /
  Archives: /archives
rss: /rss2.xml

# Content
excerpt_link: Read More
fancybox: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: ElementsProject
google_plus:
fb_admins:
fb_app_id:

marked:
    breaks: false
